# 참고: https://dart.dev/guides/language/analysis-options
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - test/**
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - cancel_subscriptions
    - prefer_single_quotes
