name: chohyunkwon
description: 플러터 발담구기 대작전

# 버전네임(version name) : 1.0.0
# 버전코드(version code) : 1
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://docs.flutter.dev/development/accessibility-and-localization/internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # iOS의 쿠퍼티노 디자인
  cupertino_icons: ^1.0.2

  # Dart lint - 설정: analysis_options.yaml
  analyzer: ^1.7.1
  # Google Fonts
  google_fonts: ^2.2.0
  # 앱 아이콘
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_grid_view: ^0.6.1

  # syncfusion 달력
  syncfusion_flutter_calendar: ^19.4.48
  # syncfusion l10n
  syncfusion_localizations: ^19.4.48
  settings_ui: ^2.0.2
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
